'use strict';
// Original bilingual template. No third-party project details or signatures are retained.
const SAFETY = {
  tasks: [
    ['housekeeping','现场整理与材料搬运','Housekeeping & material handling'],
    ['water','给水管安装（不锈钢 / PEX）','Water supply installation (stainless steel / PEX)'],
    ['waste','PVC 排水与通气管安装','PVC waste & vent installation'],
    ['fixtures','卫生洁具安装','Sanitary fixture installation'],
    ['supports','管道支架、钻孔与高处作业','Pipe supports, drilling & access at height'],
    ['gas','燃气管道与设备（授权人员专用）','Gas pipework & appliances (authorised personnel only)']
  ],
  // Each row: group, Chinese step / hazard / controls, English step / hazard / controls.
  steps: [
    ['housekeeping','开工前检查现场与通道','绊倒、滑倒、孔洞、移动设备及其他工种交叉作业。','与总包协调作业区域；检查地面、照明和逃生通道；设置隔离及警示；确认孔洞盖板和防护；发现不安全情况立即停止。','Inspect work area and access before starting','Trips, slips, openings, mobile plant and overlapping work by other trades.','Coordinate with the principal contractor; inspect ground, lighting and escape routes; isolate work zones; verify opening covers and protection; stop if conditions are unsafe.'],
    ['housekeeping','搬运材料与洁具','肌肉拉伤、挤压、尖锐边缘及负载掉落。','评估重量、形状、路线及个人能力；优先使用推车或机械辅助；需要时团队搬运，约定口令；保持负载稳定。没有适用于所有人的统一安全重量。','Move materials and fixtures','Musculoskeletal strain, crushing, sharp edges and dropped loads.','Assess weight, shape, route and individual capability; prefer trolleys or mechanical aids; use coordinated team lifting when needed; secure loads. There is no universal safe lifting weight.'],
    ['housekeeping','堆放材料','堆垛倒塌、滚动管材、堵塞通道及楼板超载。','使用支架和挡块固定管材；遵守地面或楼板承载限制；远离边缘和孔洞；保持消防设施及通道畅通。','Stack and store materials','Collapsing stacks, rolling pipes, blocked routes and overloaded floors.','Use racks and chocks; observe floor load limits; keep away from edges and openings; maintain clear routes and access to fire equipment.'],
    ['housekeeping','清理废料和施工粉尘','割伤、绊倒、粉尘吸入及化学废物暴露。','随作业清理；分类收集尖锐及化学废料；使用合适的抽尘设备或湿式方法，避免干扫及压缩空气扬尘；按 SDS 和现场规则处置。','Remove waste and construction dust','Cuts, trips, inhalation of dust and chemical waste exposure.','Clean as work progresses; segregate sharp and chemical waste; use suitable extraction or wet methods, avoiding dry sweeping and compressed-air dust dispersal; dispose according to SDS and site rules.'],
    ['water','测量、切割和安装不锈钢管','切割伤、飞屑、噪声、火花及长管搬运。','固定管材；使用符合制造商要求的工具和防护罩；切后去毛刺；使用合适护目和听力防护；处理锋利边缘时戴防割手套，旋转工具旁按制造商要求处理手套风险；涉及火花先评估热作许可。','Measure, cut and fit stainless-steel pipe','Cuts, flying debris, noise, sparks and handling long pipes.','Secure pipe; use tools and guards as specified by the manufacturer; deburr ends; use suitable eye and hearing protection; wear cut-resistant gloves for sharp edges, managing entanglement risks near rotating tools per instructions; assess hot-work permits for sparks.'],
    ['water','压接或螺纹连接','夹手、手部劳损、金属屑及接头失效。','选用匹配管件的工具和模具；检查维护或校准要求；手远离夹点；检查接头完成情况；加压前检查所有连接。','Press-fit or thread pipe connections','Pinch injuries, hand strain, swarf and joint failure.','Use tools and jaws matched to fittings; verify maintenance or calibration requirements; keep hands clear of pinch points; inspect completed joints before pressurisation.'],
    ['water','切割、安装和连接 PEX 管','刀具割伤、夹点、搬运劳损及错误接头。','使用合适且维护良好的 PEX 切管器；手远离刀刃；选用制造商认可的管材、管件及连接工具；逐个检查接头；隐蔽前试验。','Cut, fit and connect PEX pipe','Blade cuts, pinch points, handling strain and incorrect fittings.','Use suitable maintained PEX cutters; keep hands clear of blades; use manufacturer-approved pipe, fittings and joining tools; inspect every joint and test before concealment.'],
    ['water','系统压力试验','储能释放、管件弹出、管道破裂及积水滑倒。','按批准的试验程序及制造商限制操作；使用适合的仪表；隔离试验区，缓慢加压，避开端盖及接头正前方；确认隔离阀位置；处理漏水前卸压；气压试验须另行专项评估。','Pressure-test the system','Stored energy release, ejected fittings, pipe failure and wet-floor slips.','Follow the approved test procedure and manufacturer limits; use suitable gauges; isolate the test zone, increase pressure gradually and keep clear of end caps and joints; locate isolation valves; depressurise before repairs; separately assess pneumatic testing.'],
    ['waste','切割 PVC 管','割伤、飞屑、噪声及旋转工具夹卷。','将管材固定在支架或台钳上；检查工具及防护罩；使用合适的护目和听力防护；手远离切割线，按制造商说明操作。','Cut PVC pipe','Cuts, flying debris, noise and entanglement in rotating tools.','Secure pipe on stands or in a vice; inspect tools and guards; use appropriate eye and hearing protection; keep hands clear and follow manufacturer instructions.'],
    ['waste','使用 PVC 底漆及溶剂胶','蒸气吸入、眼皮肤刺激及火灾。','查阅实际产品 SDS；优先选用较低危害产品；提供通风；远离点火源；及时盖好容器；选用 SDS 指定的化学防护手套与护目镜；准备泄漏处理物资。','Apply PVC primer and solvent cement','Vapour inhalation, eye/skin irritation and fire.','Review the actual product SDS; prefer lower-hazard products; ventilate; exclude ignition sources; reseal containers; use chemical gloves and eyewear specified by SDS; provide spill materials.'],
    ['waste','对齐并连接排水管','别扭姿势、过度伸展及狭小空间作业。','先规划管线及作业顺序；调整工作高度；必要时使用护膝并轮换姿势；保持逃生通道；如属于受限空间，停止并启用专项评估与许可。','Align and join waste pipe','Awkward posture, overreaching and restricted access.','Plan pipe runs and sequence; adjust work height; use knee protection and vary posture as needed; maintain escape access; if a confined space is involved, stop and use a separate assessment and permit.'],
    ['waste','通气管及墙体、楼板穿孔','隐蔽电线或管线、坠落、粉尘及防火分隔受损。','核查服务图纸并探测；与相关人员确认隔离，探测器不能单独证明安全；选择合适工作平台；采用抽尘或湿式控制；按批准系统恢复防火封堵。','Install vents and penetrate walls or floors','Hidden services, falls, dust and compromised fire separation.','Check service drawings and scan; confirm isolations with relevant trades—detectors alone do not prove safety; choose suitable access platforms; use extraction or wet controls; reinstate fire stopping using an approved system.'],
    ['fixtures','定位洁具','重物搬运、挤压、掉落及陶瓷锐边。','使用推车、吸盘或适用机械辅助；评估团队搬运；保护锐边；手远离夹点；将洁具稳定支撑后再连接。','Position sanitary fixtures','Heavy handling, crushing, dropped fixtures and sharp ceramic edges.','Use trolleys, suction lifters or suitable mechanical aids; assess team lifting; protect sharp edges; keep hands clear of pinch points; support fixtures securely before connecting.'],
    ['fixtures','连接供水及排水','漏水滑倒、意外通水及过度拧紧损坏。','确认隔离并卸压；使用接水盘；按实际管件制造商扭矩要求安装，不采用统一拧紧圈数；及时清理溢水。','Connect water and waste','Wet-floor slips, unexpected water release and damage from overtightening.','Confirm isolation and depressurise; use drip trays; follow torque requirements for the actual fittings rather than a universal turn count; clean spills promptly.'],
    ['fixtures','密封及功能测试','密封胶刺激、蒸气、漏水和积水。','查阅密封胶 SDS，使用合适手套及通风；检查可见连接；保持隔离阀可达；逐步试水并备好接水及清洁用品。','Seal and function-test fixtures','Sealant irritation, vapours, leaks and flooding.','Review sealant SDS and use suitable gloves and ventilation; inspect visible connections; keep isolation valves accessible; test progressively with spill and cleaning materials ready.'],
    ['supports','钻孔及固定管道支架','带电服务、飞屑、硅尘、振动和噪声。','核查服务图纸、探测及隔离；固定工件；采用工具抽尘或湿式方法；控制噪声及振动暴露；依据暴露评估选择呼吸防护并适配密合性；隔离旁人。','Drill and fix pipe supports','Live services, flying debris, silica dust, vibration and noise.','Verify drawings, detection and isolation; secure workpieces; use on-tool extraction or wet methods; control noise and vibration exposure; select respiratory protection from exposure assessment and ensure fit; exclude bystanders.'],
    ['supports','使用梯子或工作平台','坠落、过度伸展、失稳及坠物。','先考虑地面作业或有防护的平台；梯子仅用于适合的短时轻量任务；检查、固定并按制造商要求设置；保持安全接触，避免侧向伸展；作业区隔离。任何高度有坠落风险均需控制。','Use ladders or access platforms','Falls, overreaching, instability and dropped objects.','First consider ground-level work or a protected platform; use ladders only for suitable short-duration light tasks; inspect, secure and set up per manufacturer instructions; maintain safe contact and avoid side-reaching; isolate below. Control fall risk at any height.'],
    ['gas','安装燃气管道','燃气泄漏、火灾、爆炸及误操作。','仅由具备适用现行执照或合法授权并按所需监督条件工作的人员执行；确认气源隔离；使用批准材料；按程序试漏；禁用明火试漏；控制点火源。','Install gas pipework','Gas leaks, fire, explosion and unauthorised work.','Only personnel with the applicable current licence or lawful authorisation and required supervision may perform the work; confirm gas isolation; use approved materials; test for leaks to the procedure; never use a flame for leak testing; control ignition sources.'],
    ['gas','连接燃气设备','连接错误、泄漏、一氧化碳及通风不足。','确认设备与气种、压力匹配；遵守制造商要求；核查烟道及通风；在启用前完成规定的气密性及安全测试；保留所需记录。','Connect gas appliances','Incorrect connections, leaks, carbon monoxide and inadequate ventilation.','Verify appliance compatibility with gas type and pressure; follow manufacturer requirements; verify flues and ventilation; complete required tightness and safety testing before use; retain required records.'],
    ['gas','燃气设备调试','意外点火、不完全燃烧及一氧化碳暴露。','由适当授权人员按批准程序调试、置换及燃烧检查；通知受影响人员；配备适用检测仪器；异常立即停止、隔离并通风；完成适用的证书与交付。','Commission gas appliances','Unexpected ignition, incomplete combustion and carbon monoxide exposure.','Appropriately authorised personnel must follow approved commissioning, purging and combustion-check procedures; inform affected people; provide suitable instruments; stop, isolate and ventilate on abnormal results; complete applicable certification and handover.']
  ],
  ppe:[['boots','安全鞋','Safety footwear'],['hiVis','高可视服','High-visibility clothing'],['hardHat','安全帽（按现场要求）','Hard hat (site requirements)'],['eye','护目镜','Eye protection'],['cutGloves','防割手套（匹配作业）','Cut-resistant gloves (task suitable)'],['chemicalGloves','化学防护手套（按 SDS）','Chemical gloves (per SDS)'],['hearing','听力防护','Hearing protection'],['respirator','呼吸防护（评估及密合）','Respiratory protection (assessment & fit)'],['knees','护膝','Knee protection']],
  checks:[
    ['site','已与受影响工人讨论现场风险、工作顺序及控制措施。','Affected workers have discussed site hazards, work sequence and controls.'],
    ['sssp','已审核现场专项安全计划（SSSP）、总包要求及相关服务隔离。','The SSSP, principal contractor requirements and relevant service isolations have been reviewed.'],
    ['permits','已确认适用许可、SDS、工具及人员资质；不适用项目已在下方说明。','Applicable permits, SDS, equipment and competencies are confirmed; exclusions are recorded below.'],
    ['controls','已在现场实施并检查控制措施，完成初始及剩余风险评估。','Controls are implemented and checked on site, and initial/residual risk assessments are complete.'],
    ['emergency','已说明紧急联络、急救、集合点和停工程序。','Emergency contacts, first aid, assembly point and stop-work arrangements have been explained.'],
    ['review','负责人确认本版本适用于本次作业；条件或人员变化时重新评估并交底。','The responsible person confirms this revision suits the work; reassess and rebrief when conditions or workers change.']
  ]
};
